name: Deploy Docusaurus to GitHub Pages

on:
  push:
    branches:
      - main

permissions:  # ✅ Ensures GitHub Actions has permission to push
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Required for pushing to gh-pages

      - name: Install dependencies
        run: npm install

      - name: Build website
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # ✅ Uses built-in GitHub token
          publish_dir: ./build
          publish_branch: gh-pages
